name: Docker

on:
  workflow_dispatch:

jobs:
  - uses: actions/delete-package-versions@v5
    with: 
      package-name: 'novusmail'
      package-type: 'container'
      min-versions-to-keep: 10
      delete-only-untagged-versions: 'true'